import {
  Briefcase,
  TrendingUp,
  PenTool,
  Gift,
  Wallet,
  Receipt,
  Landmark,
  Banknote,
  PiggyBank,
  HandCoins,
  Home,
  Zap,
  ShoppingCart,
  Car,
  Utensils,
  HeartPulse,
  Tv,
  GraduationCap,
  Plane,
  ShoppingBag,
  Smartphone,
  Shirt,
  PawPrint,
  Wine,
  Dumbbell,
  Baby,
  Shield,
  Repeat,
  Gem,
  MoreHorizontal,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  "pen-tool": PenTool,
  gift: Gift,
  wallet: Wallet,
  receipt: Receipt,
  landmark: Landmark,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  "hand-coins": HandCoins,
  home: Home,
  zap: Zap,
  "shopping-cart": ShoppingCart,
  car: Car,
  utensils: Utensils,
  "heart-pulse": HeartPulse,
  tv: Tv,
  "graduation-cap": GraduationCap,
  plane: Plane,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  shirt: Shirt,
  "paw-print": PawPrint,
  wine: Wine,
  dumbbell: Dumbbell,
  baby: Baby,
  shield: Shield,
  repeat: Repeat,
  gem: Gem,
  "more-horizontal": MoreHorizontal,
}

export const ICON_NAMES = Object.keys(ICON_MAP)

export function getCategoryIcon(name: string | undefined | null): LucideIcon | null {
  if (!name) return null
  return ICON_MAP[name] ?? null
}
